# Site wide configuration

title: Jeremy's new blog
locale: en_US
description: A (mostly) technical blog of various things
logo: site-logo.png
search: true
url: http://jeremymodell.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.ru", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Jeremy Matos-Modell
  avatar: bio-photo3.jpg
  email: jeremymodell@gmail.com
  disqus-shortname: jeremystechnicalblog
  twitter: jeremymodell
  facebook: jeremymatosm
  github: jeremymodell
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  google:
    plus: 118198595497610139802
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
